apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    release: {{ .Values.app }}
    version: {{ .Values.image.imageTag }}
spec:
  replicas: {{ .Values.hpa.minReplicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
      release: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        release: {{ .Values.app }}
        version: {{ .Values.image.imageTag }}
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.repoURL }}:{{ .Values.image.imageTag }}"
          imagePullPolicy: Always
          ports:
          # web port
          - containerPort: 8080
      imagePullSecrets:
      # harbor secret in eks dockerconfigjson
      # setting as jane's account for now
      - name: harbor-registry-secret
