app: demo-service
namespace: default

image:
  repoURL: aws.registry.trendmicro.com/soter/actions_demo
  imageTag: __FROM_HELM_SET__

hpa:
  minReplicas: __FROM_VALUES_FILE__
  maxReplicas: __FROM_VALUES_FILE__

podDisruptionBudget:
  maxUnavailable: 1 # pls confirm replicas need large then 2
