name: robot

on: 
  push:
  workflow_dispatch:
    
jobs:

  robot-job:
    runs-on: ubuntu-latest
    env:
      l1-test-check: false
    # job steps
    steps:

      # sync repo
      - uses: actions/checkout@v2

      - name: Docker Hub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: l1-testing
        run: |
          cd robot
          docker-compose up -d
          sleep 5s
          docker-compose down
          [ -f reports/test.html ] && ${{ env.l1-test-check }}=true && echo "[ Robot-Debug ] l1-testing is finished" || echo "[ Robot-Debug ] log file not exists"
          cd -

      - name: l1-test report check
        if: ${{ env.l1-test-check }} != true
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('env.l1-test-check and true are not equivalent!')

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot-reports
          path: robot/reports/

      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: robot-reports

      # publish test report
      - name: publish l1-test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'robot-reports/xunit.xml' # test file name filter method
          report_individual_runs: "true"
          check_name: "l1 Test Results"
