name: robot

on: 
  push:
  workflow_dispatch:
    
jobs:

  robot-job:
    runs-on: ubuntu-latest
    # job steps
    steps:

      # sync repo
      - uses: actions/checkout@v2

      - name: Docker Hub login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: l1-testing
        run: |
          cd robot
          docker-compose up -d
          timeout=10
          while [ ! -f reports/xunit.xml ];
          do
            if [ "$timeout" == 0 ]; then
              docker-compose down
              echo "ERROR: Timeout while waiting for the file reports/xunit.xml."
              exit 1
            fi
            sleep 1
            ((timeout--))
            echo "[ Robot-Debug ] waiting for reports generate: remaining $timeout sec."
          done
          docker-compose down
          echo "[ Robot-Debug ] reports/xunit.xml file found"
          echo "[ Robot-Debug ] l1-testing is finished"
          cd -

      - name: l1-test report check
        if: hashFiles('robot/reports/xunit.xml') == ''
        uses: actions/github-script@v3
        with:
          script: |
              core.setFailed('[ Robot-Debug ] log file not exists ')

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot-reports
          path: robot/reports/

      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: robot-reports

      # publish test report
      - name: publish l1-test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'robot-reports/xunit.xml' # test file name filter method
          report_individual_runs: "true"
          check_name: "l1 Test Results"
