name: robot

on: 
  push:
  workflow_dispatch:
    
jobs:

  robot-job:
    runs-on: ubuntu-latest
    # job steps
    env:
      MY_ENV_VAR: true
      MY_ENV_VAR_F: false
      MY_ENV_VAR_IF: 'Jane'
    steps:

      - uses: actions/hello-world-javascript-action@v1.1
        if: ${{ env.MY_ENV_VAR }}

      - name: test-2
        uses: actions/hello-world-javascript-action@v1.1
        if: ${{ env.MY_ENV_VAR_F }}

      - name: if
        if: contains(['J'],env.MY_ENV_VAR_IF)
        run:  echo "YES"